config/routes.rb
Rails.application.routes.draw do
  
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # material routes only for moderator and admin
  namespace :moderator do
    resources :faculties do 
      resources :courseofstudies
      resources :assoziations
      # Route for AJAX - Request
      get 'assoziations/:studytype_id/dropdown',
          to: "assoziations#dropdown",
          as: 'dropdown'
      resources :lectures
      resources :connections
       resources :materials
    end
    
    resources :studytypes
    resources :categories
    resources :sections
   
    resources :notificationtypes do
      resources :notifications
    end
    
    resources :galleries do
      resources :images
    end
    
  end
  
  
  # material routes for user 
  namespace :user do
    # route 1 and route 2
    resources :faculties, only: [:index, :show]
    
    # route 3
    get 'faculty_courseofstudies/:faculty_id',
        to: 'faculty_courseofstudies#index',
        :as => 'faculty_courseofstudies'
    # route 4
    get 'faculty_courseofstudies/:faculty_id/:courseofstudy_id',
        to: 'faculty_courseofstudies#show',
        :as => 'faculty_courseofstudy'
        
    # route 5
    get 'category_lectures/:faculty_id/:category_id/:courseofstudy_id',
         to: 'category_lectures#index',
         :as => 'category_lectures'
    # route 6
    get 'category_lectures/:faculty_id/:category_id/:courseofstudy_id/:id',
         to: 'category_lectures#show', 
         :as => 'category_lecture'
         
    # route 7
    get 'courseofstudy_categories/:faculty_id/:courseofstudy_id',
        to: 'courseofstudy_categories#index',
        :as => 'courseofstudy_categories'
    # route 8
    get 'courseofstudy_categories/:faculty_id/:courseofstudy_id/:id',
        to: 'courseofstudy_categories#show',
        :as => 'courseofstudy_category'
    
    # route 9     
    get 'section_materials/:category_id/:courseofstudy_id/:lecture_id/:section_id',
         to: 'section_materials#index',
         :as => 'section_materials'
    # route 10     
    get 'section_materials/:category_id/:courseofstudy_id/:lecture_id/:section_id/:id',
         to: 'section_materials#show',
         :as => 'section_material'
         
    # route 11
    get 'lecture_sections/:category_id/:lecture_id/:courseofstudy_id',
         to: 'lecture_sections#index',
         :as => 'lecture_sections'
    # route 12
    get 'lecture_sections/:category_id/:lecture_id/:courseofstudy_id/:id',
         to: 'lecture_sections#show',
         :as => 'lecture_section'
         
    # Gallery Section
    get 'galleries/:gallery_id',
         to: 'galleries#index',
         as: 'galleries'
         
    # News Section
    get 'news/:notificationtype_id',
         to: 'notifications#index',
         as: 'news'
    get 'news/:notificationtype_id/:notification_id',
         to: 'notifications#show',
         as: 'new'
  end
  
  # verstecke den user_controller im admin - Ordner
  namespace :admin do
    resources :users, only: [:edit, :update, :destroy, :index] 
  end
  
  resources :profiles
  
  # change the default routes at devise
  devise_for :users, path: '',
    path_names:
    { 
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
    }
  
  root to: 'home#index'
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  
  has_one :profile
    
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :moderator], multiple: false)                              ##
  ############################################################################################ 
 
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
         
  
  # variable area

        
  # add attributes validation
  validates_presence_of :username
  
  
  # read the current role name
  def get_role_name
    length = self.roles.to_s.length
    if length == 7
      role = "user"
    else if length == 19
      role = "moderator"
    else
      role = "admin"
    end
    end
  end
  
  # check if admin
  def is_admin
    self.roles != 7 && self.roles != 19
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
   
  before_action :set_user, only: [:show, :edit, :update, :destroy] 
   
  # set access roles
  access user: {except: [:destroy, :new, :create, :update, :edit, :show, :index]},
  moderator:   {except: [:destroy, :new, :create, :update, :edit, :show, :index]},
  admin:       {except: [:new, :create, :show]}
   
  def index 
    @users = User.all
  end
  
  def new
    # out of order 
  end
  
  def edit 
    
  end
  
  def show
    # out of order
  end
  
  def create
    # out of order
  end
  
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admin_users_path, notice: 'User was successfully updated.' }
        format.json { render :admin_users_path, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  
  private 
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    
    # Never trust parameters from the evil internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :roles)
    end
    
end

app/controllers/user/categories_controller.rb
class User::CategoriesController < ApplicationController
  
  before_action :set_category, only: [:show]
  
  # set access roles
  access user: {except: [:destroy, :new, :create, :update, :edit]}
  
  #GET /user/
  def index
  end
  
  def show
  end
  
  private
  
  def set_category
  end
end

app/controllers/user/category_lectures_controller.rb
class User::CategoryLecturesController < ApplicationController
  
  before_action :get_data, only: [:index, :show]
  
  # set access roles
  access user: {except: [:destroy, :new, :create, :update, :edit]}
    
  # GET user/category_lectures/faculty_id/category_id/courseofstudy_id
  def index
  end
  
  # GET user/category_lectures/faculty_id/category_id//courseofstudy_id/lecture_id
  def show
    @lecture = Lecture.find(params[:id])
    @assoziation = @lecture.assoziations.first
    @sections = @lecture.materials
  end
  
  # the private section
  private
  
    def get_data    
      @faculty = Faculty.find(params[:faculty_id])
      @courseofstudy = Courseofstudy.find(params[:courseofstudy_id])
      @studytype = Studytype.find(@courseofstudy.studytype_id)
      @assoziations = Assoziation.where("courseofstudy_id = ? AND category_id = ?",
                                        params[:courseofstudy_id],
                                        params[:category_id])
                                        .page(params[:page])
                                        .per(@lectures_per_page)
      @category = Category.find(params[:category_id])
    end
    
end

app/controllers/user/courseofstudy_categories_controller.rb
class User::CourseofstudyCategoriesController < ApplicationController

  before_action :get_data, only: [:index, :show]
  
  # set access roles
  access user: {except: [:destroy, :new, :create, :update, :edit]}
    
  # GET /user/courseofstudies_categories/faculty_id/courseofstudy_id
  def index
  end
  
  # GET /user/courseofstudies_categories/faculty_id/courseofstudy_id/category_id
  def show
   @category = Category.find(params[:id])
  end
  
  # the private section
  private
  
    def get_data
      @faculty = Faculty.find(params[:faculty_id])
      @courseofstudy = Courseofstudy.find(params[:courseofstudy_id])
      @studytype = Studytype.find(@courseofstudy.studytype_id)
      @categories = Courseofstudy.find(params[:courseofstudy_id])
                                 .categories.distinct
                                 .page(params[:page])
                                 .per(@categories_per_page)
      @assoziations = Assoziation.where("courseofstudy_id = ?",
                                        params[:courseofstudy_id])
    end

end

app/controllers/user/faculties_controller.rb
class User::FacultiesController < ApplicationController
  
  # set access roles
  access user: {except: [:destroy, :new, :create, :update, :edit]}
    
  # GET /user/faculties/
  def index
    @faculties = Faculty.all.page(params[:page]).per(@faculties_per_page)
  end
  
  # GET user/faculties/1
  def show
    @faculty = Faculty.find(params[:id])
    @courseofstudies = @faculty.courseofstudies
  end

end

app/controllers/user/faculty_courseofstudies_controller.rb
class User::FacultyCourseofstudiesController < ApplicationController
  
  before_action :get_data, only: [:index, :show]
  
  # set access roles
  access user: {except: [:destroy, :new, :create, :update, :edit]}
  
  # GET /user/faculty_courseofstudies/faculty_id
  def index
  
  end
  
  # GET /user/faculty_courseofstudies/facult_id/courseofstudy_id
  def show
   @faculty_courseofstudy = @faculty_courseofstudies.find(params[:courseofstudy_id])
   @categories = @faculty_courseofstudy.categories.distinct
   @studytype = Studytype.find(@faculty_courseofstudy.studytype_id)
  end
  
  
  # the private section
  private
  
    def get_data
      @faculty = Faculty.find(params[:faculty_id])
      @faculty_courseofstudies = @faculty.courseofstudies.page(params[:page])
                                         .per(@courseofstudies_per_page)
    end
  
end

app/controllers/user/galleries_controller.rb
class User::GalleriesController < ApplicationController
  
  before_action :get_data, only: [:index, :show]
  
  # set access roles
  access user: {except: [:destroy, :new, :create, :update, :edit]}
  
  # GET /user/galleries/gallery_id
  def index 
     @galleries = Gallery.all
     @gallery = @galleries.find(params[:gallery_id])
     @images = @gallery.images.page(params[:page]).per(@images_per_page)
  end
  
  # GET /user/galleries/1
  def show
  
  end
  
  # the private section
  private
  
    def get_data
     
    end
end

app/controllers/user/lecture_sections_controller.rb
class User::LectureSectionsController < ApplicationController
  
  before_action :get_data, only: [:index, :show]
  
  # set access roles
  access user: {except: [:destroy, :new, :create, :update, :edit]}
  
  # GET  /user/lecture_sections/1/1
  def index
    @sections = @lecture.materials.page(params[:page]).per(@sections_per_page)
  end
  
  # GET /user/lecture_sections/1/1/1
  def show
    @section = @lecture.materials.find(params[:id])
    @materials = Material.where("lecture_id = ? AND section_id = ?",
                                params[:lecture_id], @section)
  end
  
  # the private section
  private
  
  def get_data
    @courseofstudy = Courseofstudy.find(params[:courseofstudy_id])
    @faculty_id = @courseofstudy.faculty_id
    @faculty = Faculty.find(@faculty_id)
    @category = Category.find(params[:category_id])
    @lecture = Lecture.find(params[:lecture_id])
    @studytype = Studytype.find(@courseofstudy.studytype_id)
  end
  
end

app/controllers/user/notifications_controller.rb
class User::NotificationsController < ApplicationController
  
  
  
  # set access roles
  access user: {except: [:destroy, :new, :create, :update, :edit]}
  
  # GET /user/news/:notificationtype_id
  def index
    @notifications = Notification.all.page(params[:page]).per(3)
    @notificationtypes = Notificationtype.all
    @notificationtype = @notificationtypes.find(params[:notificationtype_id])
    @notifications_per_type = @notificationtype.notifications.page(params[:page]).per(3)
  end
  
  
  def show
    @notification =  Notification.find(params[:notification_id])
  end
end

app/controllers/user/section_materials_controller.rb
class User::SectionMaterialsController < ApplicationController
  
  before_action :get_data, only: [:index, :show]
  
  # set access roles
  access user: {except: [:destroy, :new, :create, :update, :edit]}
    
  # GET /user/section_materials/category_id/courseofstudy_id/lecture_id/section_id
  def index
  end
  
  # GET /user/section_materials/category_id/courseofstudy_id/lecture_id/section_id/id
  def show
    @material = @materials.find(params[:id])
  end
  
  # the private section
  private
  
    def get_data
      @faculty_id = Courseofstudy.find(params[:courseofstudy_id]).faculty_id
      @faculty = Faculty.find(@faculty_id)
      @courseofstudy = Courseofstudy.find(params[:courseofstudy_id])
      @studytype = Studytype.find(@courseofstudy.studytype_id)
      @category = Category.find(params[:category_id])
      @lecture = Lecture.find(params[:lecture_id])
      @section = Section.find(params[:section_id])
      @materials = Material.where("lecture_id = ? AND section_id = ?",
                                   params[:lecture_id],
                                   params[:section_id])
                                   .page(params[:page])
                                   .per(@user_description_length)
    end
  
end

app/views/user/faculty_courseofstudies/index.html.erb
<!-- index - Facultity Courseofstudies -->

<br />

<div class="row">
  
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= user_faculties_path %>">Fakultäten</a>
    </li>
    <li class="breadcrumb-item active">
      <%= @faculty.symbol %></a>
     </li>
  </ol>
  
  <center><%= paginate @faculty_courseofstudies %></center>
  
  <% @faculty_courseofstudies.each do |faculty_courseofstudy| %>
    <% 
      studytype = Studytype.find(faculty_courseofstudy.studytype_id)
      categories = faculty_courseofstudy.categories.uniq
    %>
    <div class="col-lg-10 col-lg-offset-1 col-md-8 col-md-offset-2 col-sm-8">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h4 class='panel-title'>
            <span class="badge"><%= @faculty.symbol %></span>
            <span class="glyphicon glyphicon-arrow-right"></span>
            <%= faculty_courseofstudy.name %>
            <%= faculty_courseofstudy.symbol + 
                  studytype.symbol %>
          </h4>
        </div>
        <div class="panel-body user-panel-body">
          <p><%= truncate(faculty_courseofstudy.description, 
                          length: @user_description_length) %></p>
        </div>
        <div class="panel-footer user-panel-badges">
           <% categories.each do |category| %>
            <span class="badge">
              <%= link_to category.name,
                  user_category_lectures_path(params[:faculty_id], 
                                              category,
                                              faculty_courseofstudy) %>
                  &nbsp;
            </span>
          <% end %>
        </div>
        <div class='panel-footer user-panel-actions'>
          <a class='btn btn-default' 
             href="<%= user_courseofstudy_categories_path(params[:faculty_id],
                                                          faculty_courseofstudy) %>">
            <span class=" glyphicon glyphicon-education"></span>
             Kategorien
            <span class=" glyphicon glyphicon-menu-right"></span>
            <span class="badge">
             <%= categories.count %>
            </span></a>
          <a class="btn btn-default"
              href="<%= user_faculty_courseofstudy_path(params[:faculty_id],
                                                         faculty_courseofstudy) %>">
              <span class="glyphicon glyphicon-eye-open"></span>
              Details
          </a>
        </div>
      </div>
    </div>
  <% end %>
    
  <center><%= paginate @faculty_courseofstudies %></center>
  
</div>

<br />
<center>
  <a class='btn btn-default' 
     href="<%= user_faculties_path %>">
    <span class="glyphicon glyphicon-share"></span> 
     Fakultäten
  </a>
</center>

app/views/user/faculty_courseofstudies/show.html.erb
<!-- show - Facultity Courseofstudies -->

<br />

<div class="row">
  
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="<%= user_faculties_path %>">Fakultäten</a>
    </li>
    <li class="breadcrumb-item">
     <a href="<%= user_faculty_courseofstudies_path(params[:faculty_id]) %>">
          <%= @faculty.symbol %></a>
     </li>
    <li class="breadcrumb-item active">
       <%= @faculty_courseofstudy.symbol + @studytype.symbol %>
    </li>
  </ol>
  
  <br /><br />
  
  <div class="col-lg-10 col-lg-offset-1 col-md-8 col-md-offset-2 col-sm-8">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h4 class='panel-title'>
            <span class="badge"><%= @faculty_courseofstudy.symbol +
                                    @studytype.symbol %></span>
            <span class="glyphicon glyphicon-arrow-right"></span>
            <%= @faculty_courseofstudy.name %>
          </h4>
        </div>
        <div class="panel-body user-panel-body">
          <p><%= @faculty_courseofstudy.description %></p>
        </div>
        <div class="panel-footer user-panel-badges">
          <% @categories.each do |category| %>
            <span class="badge">
              <%= category.name %>  
            </span> 
          <% end %>
        </div>
        <div class='panel-footer user-panel-actions'>
          <a class='btn btn-default' 
             href="<%= user_faculty_courseofstudies_path %>">
            <span class="glyphicon glyphicon-share"></span> 
             Studiengänge
          </a>
          <a class='btn btn-default' 
             href="<%=user_faculties_url(params[:faculty_id]) %>">
            <span class="glyphicon glyphicon-share"></span> 
             Fakultäten
          </a>
        </div>
    </div>    
  </div>
 
</div>        
  