config/routes.rb
Rails.application.routes.draw do
  
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # material routes only for moderator and admin
  namespace :moderator do
    resources :faculties do 
      resources :courseofstudies
      resources :assoziations
      # Route for AJAX - Request
      get 'assoziations/:studytype_id/dropdown',
          to: "assoziations#dropdown",
          as: 'dropdown'
      resources :lectures
      resources :connections
       resources :materials
    end
    
    resources :studytypes
    resources :categories
    resources :sections
   
    resources :notificationtypes do
      resources :notifications
    end
    
    resources :galleries do
      resources :images
    end
    
  end
  
  
  # material routes for user 
  namespace :user do
    # route 1 and route 2
    resources :faculties, only: [:index, :show]
    
    # route 3
    get 'faculty_courseofstudies/:faculty_id',
        to: 'faculty_courseofstudies#index',
        :as => 'faculty_courseofstudies'
    # route 4
    get 'faculty_courseofstudies/:faculty_id/:courseofstudy_id',
        to: 'faculty_courseofstudies#show',
        :as => 'faculty_courseofstudy'
        
    # route 5
    get 'category_lectures/:faculty_id/:category_id/:courseofstudy_id',
         to: 'category_lectures#index',
         :as => 'category_lectures'
    # route 6
    get 'category_lectures/:faculty_id/:category_id/:courseofstudy_id/:id',
         to: 'category_lectures#show', 
         :as => 'category_lecture'
         
    # route 7
    get 'courseofstudy_categories/:faculty_id/:courseofstudy_id',
        to: 'courseofstudy_categories#index',
        :as => 'courseofstudy_categories'
    # route 8
    get 'courseofstudy_categories/:faculty_id/:courseofstudy_id/:id',
        to: 'courseofstudy_categories#show',
        :as => 'courseofstudy_category'
    
    # route 9     
    get 'section_materials/:category_id/:courseofstudy_id/:lecture_id/:section_id',
         to: 'section_materials#index',
         :as => 'section_materials'
    # route 10     
    get 'section_materials/:category_id/:courseofstudy_id/:lecture_id/:section_id/:id',
         to: 'section_materials#show',
         :as => 'section_material'
         
    # route 11
    get 'lecture_sections/:category_id/:lecture_id/:courseofstudy_id',
         to: 'lecture_sections#index',
         :as => 'lecture_sections'
    # route 12
    get 'lecture_sections/:category_id/:lecture_id/:courseofstudy_id/:id',
         to: 'lecture_sections#show',
         :as => 'lecture_section'
         
    # Gallery Section
    get 'galleries/:gallery_id',
         to: 'galleries#index',
         as: 'galleries'
         
    # News Section
    get 'news/:notificationtype_id',
         to: 'notifications#index',
         as: 'news'
    get 'news/:notificationtype_id/:notification_id',
         to: 'notifications#show',
         as: 'new'
  end
  
  # verstecke den user_controller im admin - Ordner
  namespace :admin do
    resources :users, only: [:edit, :update, :destroy, :index] 
  end
  
  resources :profiles
  
  # change the default routes at devise
  devise_for :users, path: '',
    path_names:
    { 
      sign_in: 'login',
      sign_out: 'logout',
      sign_up: 'register'
    }
  
  root to: 'home#index'
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :gallery
  
  has_attached_file :picture, styles: { medium: "300x300", thumb: "100x100", thumb_gallery: "200x200" }, 
  default_url: "/system/notifications/images/000/000/001/thumb/150x150?1505070152"
  # Validate content type
  validates_attachment_content_type :picture, content_type:  /\Aimage\/.*\z/
  
   # https://s3-eu-west-1.amazonaws.com/a9s-railsvorlesung/home/railsvorlesung4//images/pictures/000/000/003/medium/Bild_2.jpg?1506099552
   # https://s3.amazonaws.com/a9s-railsvorlesung/home/railsvorlesung4//images/pictures/000/000/001/thumb/pretzel-2759994__340_1_.jpg?1506111096
 
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  
   # set access roles
  access all: [:show, :index], 
  user:  {except: [:destroy, :new, :create, :update, :edit]},
  moderator: :all,
  admin: :all

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
    @image.gallery_id = Gallery.find(params[:id]).id
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :picture, :gallery_id)
    end
end

app/controllers/moderator/assoziations_controller.rb
class Moderator::AssoziationsController < ApplicationController
  before_action :set_assoziation, only: [:show, :edit, :update, :destroy]
  #respond_to :html, :js
  # set access roles
  access moderator:   :all,
  admin:       :all
  
 

  # GET /assoziations
  # GET /assoziations.json
  def index
    @faculties = Faculty.all
    @faculty = @faculties.find(params[:faculty_id])
    @courseofstudies = Courseofstudy.where(faculty_id: params[:faculty_id])
    @assoziations = Assoziation.where(courseofstudy_id: get_courseofstudy_ids(@courseofstudies))
  end

  # GET /assoziations/1
  # GET /assoziations/1.json
  def show
  end

  # GET /assoziations/new
  def new
    @assoziation = Assoziation.new
  end

  # GET /assoziations/1/edit
  def edit
    @courseofstudy = Courseofstudy.find(@assoziation.courseofstudy_id) 
  end

  # POST /assoziations
  # POST /assoziations.json
  def create
    @assoziation = Assoziation.new(assoziation_params)

    respond_to do |format|
      if @assoziation.save
        format.html { redirect_to moderator_faculty_assoziations_path(params[:faculty_id]), 
                      notice: 'Assoziation was successfully created.' 
        }
        format.json { render :show, status: :created, location: @assoziation }
      else
        format.html { render :new }
        format.json { render json: @assoziation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assoziations/1
  # PATCH/PUT /assoziations/1.json
  def update
    respond_to do |format|
      if @assoziation.update(assoziation_params)
        format.html { redirect_to moderator_faculty_assoziations_path(params[:faculty_id]),
                      notice: 'Assoziation was successfully updated.' }
        format.json { render :show, status: :ok, location: @assoziation }
      else
        format.html { render :edit }
        format.json { render json: @assoziation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assoziations/1
  # DELETE /assoziations/1.json
  def destroy
    @assoziation.destroy
    respond_to do |format|
      format.html { redirect_to moderator_faculty_assoziations_url(params[:faculty_id]), 
                    notice: 'Assoziation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # for AJAX call
  def dropdown
   # @courseofstudies = Studytype.find(params[:studytype_id]).courseofstudies
    @courseofstudies = Studytype.find(params[:studytype_id]).courseofstudies
    @courseofstudies = @courseofstudies.where(faculty_id: params[:faculty_id])
    render :json => @courseofstudies.to_json()
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assoziation
      @assoziation = Assoziation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assoziation_params
      params.require(:assoziation).permit(:code, :instructor, :category_id, :courseofstudy_id, :lecture_id)
    end
    
    # gets an array of courseofstudies ids back
    def get_courseofstudy_ids courseofstudies
      i = 0
      ids = Array.new
      courseofstudies.each do |courseofstudy|
        ids.insert(i, courseofstudy.id)
        i = i + 1
      end
    end
  
end

app/controllers/moderator/categories_controller.rb
class Moderator::CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  
  # set access roles
 #  access user: {except: [:destroy, :new, :create, :update, :edit]},
  access moderator:   :all,
  admin:       :all

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to moderator_categories_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to moderator_categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to moderator_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :symbol, :description)
    end
end

app/controllers/moderator/connections_controller.rb
class Moderator::ConnectionsController < ApplicationController
  before_action :set_connection, only: [:show, :edit, :update, :destroy]
  
  # set access roles
  # access user: {except: [:destroy, :new, :create, :update, :edit]},
  access moderator:   :all,
  admin:              :all
  

  # GET /connections
  # GET /connections.json
  def index
    @faculties = Faculty.all
    @faculty = @faculties.find(params[:faculty_id])
    @connections = Connection.where(faculty_id: @faculty.id)
  end

  # GET /connections/1
  # GET /connections/1.json
  def show
  end

  # GET /connections/new
  def new
    @connection = Connection.new
  end

  # GET /connections/1/edit
  def edit
  end

  # POST /connections
  # POST /connections.json
  def create
    @connection = Connection.new(connection_params)

    respond_to do |format|
      if @connection.save
        format.html { redirect_to moderator_faculty_connections_path(params[:faculty_id]), 
                      notice: 'Connection was successfully created.' }
        format.json { render :show, status: :created, location: @connection }
      else
        format.html { render :new }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /connections/1
  # PATCH/PUT /connections/1.json
  def update
    respond_to do |format|
      if @connection.update(connection_params)
        format.html { redirect_to moderator_faculty_connections_path(params[:faculty_id]),
                      notice: 'Connection was successfully updated.' }
        format.json { render :show, status: :ok, location: @connection }
      else
        format.html { render :edit }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /connections/1
  # DELETE /connections/1.json
  def destroy
    @connection.destroy
    respond_to do |format|
      format.html { redirect_to moderator_faculty_connections_url(params[:faculty_id]),
                    notice: 'Connection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_connection
      @connection = Connection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def connection_params
      params.require(:connection).permit(:name, :lecture_id, :section_id, :faculty_id)
    end
end

app/controllers/moderator/courseofstudies_controller.rb
class Moderator::CourseofstudiesController < ApplicationController
  before_action :set_courseofstudy, only: [:show, :edit, :update, :destroy]
  
  # set access roles
  access user: {except: [:destroy, :new, :create, :update, :edit]},
  moderator:   :all,
  admin:       :all

  # GET /courseofstudies
  # GET /courseofstudies.json
  def index
    @faculties = Faculty.all
    @faculty = @faculties.find(params[:faculty_id])
    @courseofstudies = Courseofstudy.where(faculty_id: @faculty.id)
  end

  # GET /courseofstudies/1
  # GET /courseofstudies/1.json
  def show
  end

  # GET /courseofstudies/new
  def new
    @courseofstudy = Courseofstudy.new
  end

  # GET /courseofstudies/1/edit
  def edit
  end

  # POST /courseofstudies
  # POST /courseofstudies.json
  def create
    @courseofstudy = Courseofstudy.new(courseofstudy_params)

    respond_to do |format|
      if @courseofstudy.save
        format.html { redirect_to moderator_faculty_courseofstudies_path(params[:faculty_id]), 
                      notice: 'Courseofstudy was successfully created.' }
        format.json { render :show, status: :created, location: @courseofstudy }
      else
        format.html { render :new }
        format.json { render json: @courseofstudy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courseofstudies/1
  # PATCH/PUT /courseofstudies/1.json
  def update
    respond_to do |format|
      if @courseofstudy.update(courseofstudy_params)
        format.html { redirect_to moderator_faculty_courseofstudies_path(params[:faculty_id]),
                      notice: 'Courseofstudy was successfully updated.' }
        format.json { render :show, status: :ok, location: @courseofstudy }
      else
        format.html { render :edit }
        format.json { render json: @courseofstudy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courseofstudies/1
  # DELETE /courseofstudies/1.json
  def destroy
    @courseofstudy.destroy
    respond_to do |format|
      format.html { redirect_to moderator_faculty_courseofstudies_url(params[:faculty_id]),
                    notice: 'Courseofstudy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_courseofstudy
      @courseofstudy = Courseofstudy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def courseofstudy_params
      params.require(:courseofstudy).permit(:name, :symbol, :description, :faculty_id, :studytype_id)
    end
    
end

app/helpers/images_helper.rb
module ImagesHelper
  
  def create_path path
    if Rails.env.production?
      post = path.byteslice(24, path.length)
      pre = "https://s3-eu-west-1.amazonaws.com" 
      pre + "/" + post
    else
      path
    end 
  end
  
end

app/views/moderator/images/_form.html.erb
<%
  @image.id.present? ?
      path_url = moderator_gallery_image_path(params[:gallery_id], @image)
    : path_url = moderator_gallery_images_path(params[:gallery_id], @image)
%>

<%= form_for @image, url: path_url, :html => { multipart: true, :class => "form-horizontal image" } do |f| %>

  <%= render 'shared/form_errors', obj: @image %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :picture, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :picture, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :gallery_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
       <%= select_tag "image[gallery_id]", 
          options_from_collection_for_select(Gallery.all, "id", "name",
          :selected => @image.gallery_id),
          :prompt => "Please select",
          :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
        moderator_gallery_images_path(params[:gallery_id], @image), :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/moderator/images/edit.html.erb
<div class="row">
  <div class="col-lg-4 col-lg-offset-4 
              col-xs-6 col-xs-offset-3
              well well-sm
              moderator-index-header">
   <%= Gallery.find(params[:gallery_id]).name %>
  </div>
</div>
<%= render :partial => 'form' %>

app/views/moderator/images/index.html.erb
<%- model_class = Image -%>

<div class="row">
  <div class="col-lg-4 col-lg-offset-4 
              col-xs-6 col-xs-offset-3
              well well-sm
              moderator-index-header">
   <%= Gallery.find(params[:gallery_id]).name %>
  </div>
</div>

<center><%= paginate @images %></center>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:picture) %></th>
      <th><%= model_class.human_attribute_name(:gallery_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.name %></td>
        <td><%= image_tag create_path(image.picture.url(:thumb)) if image.picture %></td>
        <td><%= Gallery.find(image.gallery_id).name %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      moderator_gallery_image_path(params[:gallery_id], image),
                    :class => 'btn btn-default btn-xs action-buttons-height' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_moderator_gallery_image_path(params[:gallery_id], image),
                      :class => 'btn btn-default btn-xs action-buttons-height' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      moderator_gallery_image_path(params[:gallery_id], image),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', 
                      :default => t("helpers.links.confirm", 
                      :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger action-buttons-height' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<center><%= paginate @images %></center><br />


<%= link_to t('.new', :default => t("helpers.links.new")),
            new_moderator_gallery_image_path,
            :class => 'btn btn-primary' %>
<%= link_to 'Back', moderator_galleries_path, class: "btn btn-default" %>

app/views/moderator/images/new.html.erb
<div class="row">
  <div class="col-lg-4 col-lg-offset-4 
              col-xs-6 col-xs-offset-3
              well well-sm
              moderator-index-header">
   <%= Gallery.find(params[:gallery_id]).name %>
  </div>
</div>
<%= render :partial => 'form' %>

app/views/moderator/images/show.html.erb
<%- model_class = Image -%>

<div class="row">
  <div class="col-lg-4 col-lg-offset-4 
              col-xs-6 col-xs-offset-3
              well well-sm
              moderator-index-header">
   <%= Gallery.find(params[:gallery_id]).name %>
  </div>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @image.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:picture) %>:</strong></dt>
  <dd><%= image_tag create_path(@image.picture.url(:medium)) if @image.picture %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gallery_id) %>:</strong></dt>
  <dd><%= Gallery.find(@image.gallery_id).name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              moderator_gallery_images_path(@image.gallery_id), :class => 'btn btn-default'  %>
              
<% if logged_in?(:admin, :moderator) %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_moderator_gallery_image_path(@image.gallery_id, @image), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                moderator_gallery_image_path(@image.gallery_id, @image),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
<% end %>